site_name: Skua
theme:
  name: 'material'

nav:
- Home: index.md
- Preprocessors:
    - Introduction: 'preprocessors/introduction.md'
- Aknowledgements: aknowledgments.md
markdown_extensions:
- codehilite
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
