jobs:
  build:
    docker:
    - image: circleci/python:3.7
    steps:
    - checkout
    - run:
        name: create virtualenv
        command: |
          rm -rf venv
          python3.7 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - run:
        name: run tests
        command: source venv/bin/activate; python -m unittest tests